### ISSUE TITLE
Problem with asciidoctor-bibtex with asciidoctor 2.0.2

### ISSUE THREAD

**Issue by pela9** [asciidoctor/asciidoctor-bibtex#38] opened 2019-03-27 14:11 UTC
asciidoctor-bibtex crashes on several input files with latest asciidoctor 2.0.2. I will report this issue also in the asciidoctor archive in case this is an regression in the asciidoctor program. The stacktrace I get with asciidoctor --trace is:

```
RUBYLIB=/home/pela/svnroot/internal-tools/asciidoc-templates/db2ltx \
        asciidoctor -a docinfo=shared,private -a templatesdir=/home/pela/svnroot/internal-tools/asciidoc-templates -r asciidoctor-diagram -a blockdiag=/usr/bin/blockdiag -a dot=/usr/bin/dot -r asciidoctor-bibtex --verbose --trace  -b docbook -o makeguide.xml makeguide.adoc
/home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:113:in `gsub!': asciidoctor: FAILED: /home/pela/svnroot/QAG/dcs-make/makeguide.adoc: Failed to load AsciiDoc document - can't modify frozen String (RuntimeError)
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:113:in `block (2 levels) in process'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:112:in `each'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:112:in `block in process'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:109:in `each'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:109:in `process'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor/document.rb:557:in `[]'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor/document.rb:557:in `block in parse'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor/document.rb:556:in `each'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor/document.rb:556:in `parse'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor.rb:1301:in `load'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor.rb:1410:in `convert'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor.rb:1518:in `block in convert_file'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor.rb:1518:in `open'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor.rb:1518:in `convert_file'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor/cli/invoker.rb:126:in `block in invoke!'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor/cli/invoker.rb:109:in `each'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/lib/asciidoctor/cli/invoker.rb:109:in `invoke!'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.2/bin/asciidoctor:15:in `<top (required)>'
        from /home/pela/bin/asciidoctor:23:in `load'
        from /home/pela/bin/asciidoctor:23:in `<main>'
```

**Comment by pela9** [comment] 2019-03-27 15:05
I got the following answer from asciidoctor members:

"I think this issue should be fixed in the asciidoctor-bibtex extension by replacing text.gsub!(...) with text = text.gsub(...).
I will also allow the extension to be transpile in JavaScript with Opal as String are immutables."

We would very much appreciate a fix for this, we are relying on asciidoctor-bibtex for our document tool chain.

**Comment by ProgramFan** [comment] 2019-03-27 23:35
I will fix this later this week.

**Comment by mojavelinux** [comment] 2019-03-28 01:25
In general, `gsub!` and string manipulation should never be used. It's a poor practice because it makes the extension non-portable (and will not be compatible with Ruby 3).

**Comment by mojavelinux** [comment] 2019-03-28 01:29
@ProgramFan You might want to think about adding a build that tests against the upstream that gets triggered with each change to core. You can see an example in the reveal.js project.

* https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/.travis.yml
* https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/.travis-upstream-only.yml
* https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/Gemfile.upstream

Here's another example in Asciidoctor.js:

* https://github.com/asciidoctor/asciidoctor-diagram/blob/master/.travis.yml
* https://github.com/asciidoctor/asciidoctor-diagram/blob/master/.travis-upstream-only.yml
* https://github.com/asciidoctor/asciidoctor-diagram/blob/master/Gemfile.master

The .travis-upstream-only.yml gets merged with .travis.yml when the build is triggered by an upstream change.

**Comment by pela9** [comment] 2019-05-17 14:51
I'm well aware that this is voluntary work on your free time. But I would much appreciate a rough prognosis for when you think you could fix this problem (or state that you don't know). In the current state asciidoctor-bibtex can't be used with asciidoctor version >= 2.0, which is a shame for a nice and usefule extension library.

**Comment by mojavelinux** [comment] 2019-05-17 18:24
Since this change has to happen in asciidoctor-bibtex, because it's an incompatibility with Ruby itself, I'll submit a PR to get things moving.

**Comment by mojavelinux** [comment] 2019-05-17 18:42
I just submitted a PR to loosen the Asciidoctor dependency and replace this string modifier calls.

However, I just noticed that this project has no test suite or CI build. In fact, the test folder that's there isn't even for this project. If this situation is not corrected soon, it may be necessary to move it out of the asciidoctor organization because I have no way to guarantee that it actually works.

**Closed** 2019-05-18 08:26 UTC

**Comment by ProgramFan** [comment] 2019-05-20 16:01
Thanks for all the help. I understand the frastration caused by the inablity to use this extension with asciidoctor 2.0 caused by my late response. I am just too busy these days and not that closely tied to asciidoctor or ruby. Anyway, I will try to fixes these problems since people consider this tiny extension useful.
